package jp.numero.dagashiapp.ui.theme

import androidx.compose.ui.graphics.Color

// Generated from Material Theme Builder (Figma)
val md_theme_light_primary = Color(0xFF4f6700)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFccf15f)
val md_theme_light_onPrimaryContainer = Color(0xFF151f00)
val md_theme_light_secondary = Color(0xFF974067)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffd9e6)
val md_theme_light_onSecondaryContainer = Color(0xFF3e0021)
val md_theme_light_tertiary = Color(0xFF006494)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc8e6ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001e31)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefcf4)
val md_theme_light_onBackground = Color(0xFF1b1c17)
val md_theme_light_surface = Color(0xFFfefcf4)
val md_theme_light_onSurface = Color(0xFF1b1c17)
val md_theme_light_surfaceVariant = Color(0xFFe3e4d4)
val md_theme_light_onSurfaceVariant = Color(0xFF46483c)
val md_theme_light_outline = Color(0xFF76786a)
val md_theme_light_inverseOnSurface = Color(0xFFf3f1e9)
val md_theme_light_inverseSurface = Color(0xFF30312b)
val md_theme_light_inversePrimary = Color(0xFFb0d445)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFb0d445)
val md_theme_dark_onPrimary = Color(0xFF273500)
val md_theme_dark_primaryContainer = Color(0xFF3a4d00)
val md_theme_dark_onPrimaryContainer = Color(0xFFccf15f)
val md_theme_dark_secondary = Color(0xFFffafcf)
val md_theme_dark_onSecondary = Color(0xFF5d1138)
val md_theme_dark_secondaryContainer = Color(0xFF7a294f)
val md_theme_dark_onSecondaryContainer = Color(0xFFffd9e6)
val md_theme_dark_tertiary = Color(0xFF8aceff)
val md_theme_dark_onTertiary = Color(0xFF003450)
val md_theme_dark_tertiaryContainer = Color(0xFF004b70)
val md_theme_dark_onTertiaryContainer = Color(0xFFc8e6ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1c17)
val md_theme_dark_onBackground = Color(0xFFe5e3db)
val md_theme_dark_surface = Color(0xFF1b1c17)
val md_theme_dark_onSurface = Color(0xFFe5e3db)
val md_theme_dark_surfaceVariant = Color(0xFF46483c)
val md_theme_dark_onSurfaceVariant = Color(0xFFc6c8b8)
val md_theme_dark_outline = Color(0xFF909283)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1c17)
val md_theme_dark_inverseSurface = Color(0xFFe5e3db)
val md_theme_dark_inversePrimary = Color(0xFF4f6700)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFFa4c739)
val error = Color(0xFFba1b1b)