[versions]
androidGradlePlugin = "8.0.2"
kotlin = "1.8.21"

lifecycle = "2.6.1"
compose = "1.4.0-alpha01"
composeCompiler = "1.4.7"
material3 = "1.1.0-alpha01"

hilt = "2.44"
okhttp = "4.11.0"
accompanist = "0.27.0"

[libraries]

kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1"
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1"

androidx-annotation = "androidx.annotation:annotation:1.6.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0-alpha02"
androidx-activity = "androidx.activity:activity-compose:1.7.2"
androidx-core = "androidx.core:core-ktx:1.10.1"
androidx-coreSplash = "androidx.core:core-splashscreen:1.0.1"
androidx-window = "androidx.window:window:1.1.0"
androidx-datastore-preference = "androidx.datastore:datastore-preferences:1.0.0"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.6.0-alpha03"
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.3.1"

androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-material3WindowSizeClass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
androidx-compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

retrofit-core = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit-converter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"

okhttp3-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp3-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

coil = "io.coil-kt:coil-compose:2.2.2"

accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-swipeRefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }

composeDestinations-core = "io.github.raamcosta.compose-destinations:core:1.6.13-beta"
composeDestinations-ksp = "io.github.raamcosta.compose-destinations:ksp:1.6.13-beta"

desugarJdkLibs = "com.android.tools:desugar_jdk_libs:1.2.2"

licenses = "com.google.android.gms:play-services-oss-licenses:17.0.0"

[plugins]
androidGradlePlugin = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinPlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerializationPlugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kspPlugin = { id = "com.google.devtools.ksp", version = "1.8.21-1.0.11" }